stages:
- zip
- upload

.only: &only
  refs:
  - master
  changes:
  - src/geoalert_master_src/**
  - files/**

.cache: &cache
  key: ${CI_COMMIT_SHORT_SHA}
  paths:
  - cache

zip:
  image: alpine
  stage: zip
  cache: *cache
  only: *only
  script:
  - apk add --no-cache zip
  - mkdir -p cache
  - cp files/mapflow.xml cache/
  - cp files/techinspec.xml cache/
  - cp files/power.xml cache/
  - cd src
  - for n in $(ls);do zip -r ../cache/${n}.zip ${n};done 

upload:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: upload
  only: *only
  cache: *cache
  script:
  - cd cache
  - aws s3 sync . s3://energy-geoalert/
  - aws cloudfront create-invalidation --distribution-id=E2JFC731MVBPFE --paths "/*"
